Add support $type operator
Tinkoff/oolong pull request #27
Opened 2023-07-12 11:55 UTC by Assassin4791

### Problem

The current DSL does not support all operators yet, particularly the $type operator. 

### Solution

This merge request adds support for this operator.
The check of model fields for type is implemented using the native Scala syntax .isInstanse[T], where T should be replaced with one of the types declared in the MongoType object.

### Checklist

- [x] Unit test all changes
- [x] Update `README.md` if applicable
- [x] Add `[WIP]` to the pull request title if it's work in progress
- [x] [Squash commits](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one) that aren't meaningful changes

@oolong/maintainers

2023-07-13 18:48 UTC, edubrovski approved these changes

2023-07-17 12:20 UTC, d1skort approved these changes

2023-07-18 14:38 UTC, danslapman requested changes
Under design discussion

2023-07-18 14:45 UTC, danslapman approved these changes

2023-07-18 15:33 UTC, merged